### ISSUE TITLE
Config not saved if not present.

### ISSUE THREAD

**Issue by n00bslayr94** [DiscordBot-PMMP/ChatBridge#13]
I have `DiscordBot 3.0.2 by JaxkDev for API(s) 5.0.0` set-up in my Discord and it works fine, I followed the instructions, I can see users logging in and out. I can see chat from MC to Discord. 

When I add `ChatBridge 1.1.0 by JaxkDev for API(s) 5.0.0`, I get the following crash dump. 
I noticed that there is no config file in the plugin data folder either? I'm using the latest version of each - can you please advise?
[Wed_Oct_11-00.21.05-BST_2023.log](https://github.com/DiscordBot-PMMP/ChatBridge/files/12862792/Wed_Oct_11-00.21.05-BST_2023.log)

**Comment by JaxkDev** [comment]
Issue title is pretty misleading.

however this is a plugin issue, due to changes in config handling there is no save if no file exists now.

As a TEMPORARY work around you can add the resources/config.yml to the plugin_data/ChatBridge folder and it should load.
In next patch I will fix this to be automatic.

**Comment by JaxkDev** [comment]
[ChatBridge/resources/config.yml](https://github.com/DiscordBot-PMMP/ChatBridge/blob/stable/resources/config.yml)

**Comment by SwiftyMCPE** [comment]
```php
private function saveAllResources(): void{
        //Help files.
        $dir = scandir(Phar::running() . "/resources/help");
        if($dir === false){
            throw new PluginException("Failed to get help resources internal path.");
        }
        foreach($dir as $file){
            $this->saveResource("help/" . $file, true);
        }
    }``` i understand ur saving the help folder but where is the config.yml file

**Comment by JaxkDev** [comment]
> ```
> private function saveAllResources(): void{
>         //Help files.
>         $dir = scandir(Phar::running() . "/resources/help");
>         if($dir === false){
>             throw new PluginException("Failed to get help resources internal path.");
>         }
>         foreach($dir as $file){
>             $this->saveResource("help/" . $file, true);
>         }
>     }```
>  i understand ur saving the help folder but where is the config.yml file

It _was_ handled by pmmps config (https://github.com/DiscordBot-PMMP/ChatBridge/blob/d98deed715367028372c4a6ed75797474aa04fec/src/Main.php#L149) 
simple fix being `$this->saveResource(“config.yml”);` in save all resources.

**Comment by SwiftyMCPE** [comment]
Bro
/I

**Comment by JaxkDev** [comment]
?

**Comment by SwiftyMCPE** [comment]
static public function update(array &$config): void{. Why u used & here?

**Comment by JaxkDev** [comment]
> static public function update(array &$config): void{. Why u used & here?

Lookup `pass by reference`. I'm changing the original value not a new copy.


Locking issue as its not related to this issue.
