### ISSUE TITLE
This is not an issue report, but a feature addition request.

### ISSUE THREAD

**Issue by cherrychip8293** [DiscordBot-PMMP/ChatBridge#16]
![image](https://github.com/DiscordBot-PMMP/ChatBridge/assets/82744478/dc6cc694-ca8d-440f-9fb1-c3e6dd911435)

As shown in the picture, the nickname follows the Discord tag rather than the nickname set within the server. Can't the nickname be displayed using the nickname set on the server?

**Comment by JaxkDev** [comment]
not sure what the nickname showing in that picture is supposed to show me...


I don't understand exactly, the options `{NICKNAME}` and `{USERNAME}` already exist, note nickname falls back to username if there is no nickname set.

**Comment by cherrychip8293** [comment]
> not sure what the nickname showing in that picture is supposed to show me...
> 
> I don't understand exactly, the options `{NICKNAME}` and `{USERNAME}` already exist, note nickname falls back to username if there is no nickname set.

If my server nickname is a, I have to output it as a, but the output method is output as a Discord tag.

If my server alias is a and the tag is b, then
It outputs as b.

**Comment by JaxkDev** [comment]
DiscordBot and ChatBridge do not know what minecraft account that discord user has.

This would require integration of DiscordBot-PMMP/DiscordAccount
