### ISSUE TITLE
Bridge don't send messages FROM discord TO pmmp

### ISSUE THREAD

**Issue by Neerdex** [DiscordBot-PMMP/ChatBridge#6]
I completely and correctly setup config.yml and minecraft messages sends to the discord channes perfect! But it doesn't work in reverse side: messages from same Discord channel not sends to Minecraft chat.

P.S. Config file is default only with corrected servers and channels ID values

**Comment by JaxkDev** [comment]
Send chatbridge config file & server log (can be truncated to times when you send messages in discord)

**Comment by JaxkDev** [comment]
Also ensure on the discord developer dashboard (see the wiki for updates) that all *THREE* `privileged intents` are enabled and saved.
