### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by GabBiswajit** [DiscordBot-PMMP/ChatBridge#9]
Error: Call to a member function getDataFolder() on null
File: plugins/ChatBridge.phar/src/Main
Line: 96
Type: Error
Backtrace:
#0 plugins/ChatBridge.phar/src/Main(33): JaxkDev\ChatBridge\Main->checkOldEventsFile()

**Comment by JaxkDev** [comment]
No support for modified versions.

This should never happen, DiscordBot is a required dependency.
(And if it fails to load pmmp will stop anyway so this shouldn’t be possible)

**Comment by GabBiswajit** [comment]
Modified ?

**Comment by JaxkDev** [comment]
Also Invalid issue, follow the template.

**Comment by GabBiswajit** [comment]
When I start the server it's make crash server not start but i add the discord bot plugin discordbot dependency it's make crash server not start but i add the discord bot plugin

**Comment by JaxkDev** [comment]
Without a full log and the relevant information from a the issue templates I can’t help you

**Comment by GabBiswajit** [comment]
Wait

**Comment by GabBiswajit** [comment]
![IMG_20230721_214925](https://github.com/DiscordBot-PMMP/ChatBridge/assets/121815367/35a4ef3f-19a0-40ad-b43b-40efc7fb37cf)
Incomplete version

**Comment by JaxkDev** [comment]
There you go, plugin won’t work on PHP 8.1+

Specifically DiscordBot the dependency wont.

**Comment by GabBiswajit** [comment]
So can you update the plugin

**Comment by JaxkDev** [comment]
Its going to take a very long time.

Wouldn’t even say half way, but you can see the PR for amount of changes, its not a small task to bump DiscordPHP

https://github.com/DiscordBot-PMMP/DiscordBot/issues/88
